development:
  adapter: postgresql
  database: idead_development
  username: daveknapik
  password:
  host: localhost

test:
  adapter: postgresql
  database: idead_test
  username: daveknapik
  password:
  host: localhost
